-- SAVINGS_ACCOUNTS
CREATE TABLE SAVINGS_ACCOUNTS (
    ACCOUNT_ID   NUMBER PRIMARY KEY,
    CUSTOMER_ID  NUMBER,
    BALANCE      NUMBER(10,2)
);

-- EMPLOYEES
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID    NUMBER PRIMARY KEY,
    EMPLOYEE_NAME  VARCHAR2(100),
    DEPARTMENT     VARCHAR2(50),
    SALARY         NUMBER(10,2)
);

-- ACCOUNTS 
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID   NUMBER PRIMARY KEY,
    CUSTOMER_ID  NUMBER,
    BALANCE      NUMBER(10,2)
);
